const data=[
    {
        id:1,
        image:"/images/img1.jpg",
        like:456,
        Comment:178
    },
    {
        id:2,
        image:"/images/img2.jpg",
        like:156,
        Comment:17178
    },
    {
        id:3,
        image:"/images/img3.jpg",
        like:456,
        Comment:7778
    },
    {
        id:4,
        image:"/images/img4.jpg",
        like:416,
        Comment:178
    },
    {
        id:5,
        image:"/images/img5.jpg",
        like:456,
        Comment:7778
    },
    {
        id:6,
        image:"/images/img6.jpg",
        like:46,
        Comment:605
    },
    {
        id:7,
        image:"/images/img7.jpg",
        like:776,
        Comment:9778
    },
    {
        id:8,
        image:"/images/img8.jpg",
        like:56,
        Comment:678
    },
    {
        id:9,
        image:"/images/img2.jpg",
        like:156,
        Comment:17178
    },
]

export default data;